# fly.toml app configuration file generated for qa-lab-ecom-t2 on 2026-02-03T19:37:49+05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qa-lab-ecom-t2'
primary_region = 'ams'

[build]
  dockerfile = 'Dockerfile'

[env]
  DEBUG_MODE = 'false'
  ENV = 'prod'
  MISSION_ID = 'ecom-t2-lab'

[processes]
  app = 'uvicorn app.main:app --host 0.0.0.0 --port 8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
