"""
Registry of all 38 T2 bug flags. Values must match seed_bugs.sql exactly (UPPERCASE).
Format: FLAG{BUG_ID_XXXXXXXX}
"""

FLAGS = {
    # 3.1 Price Boundary (6)
    "PRICE_ZERO_FILTER": "FLAG{PRICE_ZERO_FILTER_A1B2C3D4}",
    "PRICE_NEGATIVE_FILTER": "FLAG{PRICE_NEGATIVE_FILTER_B2C3D4E5}",
    "PRICE_MAX_INT_OVERFLOW": "FLAG{PRICE_MAX_INT_OVERFLOW_C3D4E5F6}",
    "PRICE_FLOAT_PRECISION": "FLAG{PRICE_FLOAT_PRECISION_D4E5F6G7}",
    "PRICE_CURRENCY_MISMATCH": "FLAG{PRICE_CURRENCY_MISMATCH_E5F6G7H8}",
    "PRICE_DECIMAL_SEPARATOR": "FLAG{PRICE_DECIMAL_SEPARATOR_F6G7H8I9}",
    # 3.2 Quantity Limits (5)
    "QTY_ZERO_ADD": "FLAG{QTY_ZERO_ADD_G7H8I9J0}",
    "QTY_EXCEED_STOCK": "FLAG{QTY_EXCEED_STOCK_H8I9J0K1}",
    "QTY_MAX_CART_BYPASS": "FLAG{QTY_MAX_CART_BYPASS_I9J0K1L2}",
    "QTY_UPDATE_NEGATIVE": "FLAG{QTY_UPDATE_NEGATIVE_J0K1L2M3}",
    "QTY_FLOAT_ACCEPTED": "FLAG{QTY_FLOAT_ACCEPTED_K1L2M3N4}",
    # 3.3 Pagination & Sorting (6)
    "PAGE_NEGATIVE": "FLAG{PAGE_NEGATIVE_L2M3N4O5}",
    "PAGE_ZERO": "FLAG{PAGE_ZERO_M3N4O5P6}",
    "LIMIT_EXCESSIVE": "FLAG{LIMIT_EXCESSIVE_N4O5P6Q7}",
    "SORT_INJECTION": "FLAG{SORT_INJECTION_O5P6Q7R8}",
    "SORT_INTERNAL_FIELD": "FLAG{SORT_INTERNAL_FIELD_P6Q7R8S9}",
    "OFFSET_OVERFLOW": "FLAG{OFFSET_OVERFLOW_Q7R8S9T0}",
    # 3.4 Date Validation (5)
    "DATE_FUTURE_ORDER": "FLAG{DATE_FUTURE_ORDER_R8S9T0U1}",
    "DATE_PAST_PROMO": "FLAG{DATE_PAST_PROMO_S9T0U1V2}",
    "DATE_INVALID_FORMAT": "FLAG{DATE_INVALID_FORMAT_T0U1V2W3}",
    "DATE_TIMEZONE_ABUSE": "FLAG{DATE_TIMEZONE_ABUSE_U1V2W3X4}",
    "DATE_LEAP_YEAR": "FLAG{DATE_LEAP_YEAR_V2W3X4Y5}",
    # 3.5 String Length (5)
    "STRING_OVERLENGTH_NAME": "FLAG{STRING_OVERLENGTH_NAME_W3X4Y5Z6}",
    "STRING_EMPTY_REQUIRED": "FLAG{STRING_EMPTY_REQUIRED_X4Y5Z6A7}",
    "STRING_UNICODE_ESCAPE": "FLAG{STRING_UNICODE_ESCAPE_Y5Z6A7B8}",
    "STRING_WHITESPACE_ONLY": "FLAG{STRING_WHITESPACE_ONLY_Z6A7B8C9}",
    "STRING_SQL_IN_NAME": "FLAG{STRING_SQL_IN_NAME_A7B8C9D0}",
    # 3.6 Discount Calc (6)
    "DISCOUNT_OVER_100": "FLAG{DISCOUNT_OVER_100_B8C9D0E1}",
    "DISCOUNT_STACK_BYPASS": "FLAG{DISCOUNT_STACK_BYPASS_C9D0E1F2}",
    "DISCOUNT_EXPIRED_CODE": "FLAG{DISCOUNT_EXPIRED_CODE_D0E1F2G3}",
    "DISCOUNT_ROUNDING_ABUSE": "FLAG{DISCOUNT_ROUNDING_ABUSE_E1F2G3H4}",
    "DISCOUNT_NEGATIVE_PRICE": "FLAG{DISCOUNT_NEGATIVE_PRICE_F2G3H4I5}",
    "DISCOUNT_LOYALTY_OVERFLOW": "FLAG{DISCOUNT_LOYALTY_OVERFLOW_G3H4I5J6}",
    # 3.7 Search & Filter (5)
    "SEARCH_EMPTY_QUERY": "FLAG{SEARCH_EMPTY_QUERY_H4I5J6K7}",
    "SEARCH_SPECIAL_CHARS": "FLAG{SEARCH_SPECIAL_CHARS_I5J6K7L8}",
    "FILTER_NONEXISTENT_CATEGORY": "FLAG{FILTER_NONEXISTENT_CATEGORY_J6K7L8M9}",
    "FILTER_BOOLEAN_STRING": "FLAG{FILTER_BOOLEAN_STRING_K7L8M9N0}",
    "SEARCH_NOSQL_INJECTION": "FLAG{SEARCH_NOSQL_INJECTION_L8M9N0O1}",
}


def get_flag(bug_id: str) -> str:
    """Return flag string for bug_id or empty string if unknown."""
    return FLAGS.get(bug_id, "")
