"""
Registry of all 45 T3 bug flags. Values must match seed_bugs.sql exactly (UPPERCASE).
Format: FLAG{BUG_ID_XXXXXXXX}
"""
FLAGS = {
    # 4.1 Cart State Manipulation (5 bugs)
    "CART_STALE_TOTAL": "FLAG{CART_STALE_TOTAL_X1Y2Z3A4}",
    "CART_PROMO_PERSIST": "FLAG{CART_PROMO_PERSIST_B2C3D4E5}",
    "CART_QUANTITY_CACHE": "FLAG{CART_QUANTITY_CACHE_C3D4E5F6}",
    "CART_PRICE_FREEZE": "FLAG{CART_PRICE_FREEZE_D4E5F6G7}",
    "CART_NEGATIVE_TOTAL": "FLAG{CART_NEGATIVE_TOTAL_E5F6G7H8}",
    
    # 4.2 Order State Machine (7 bugs)
    "STATE_SKIP_PROCESSING": "FLAG{STATE_SKIP_PROCESSING_F6G7H8I9}",
    "STATE_REVERSE_DELIVERED": "FLAG{STATE_REVERSE_DELIVERED_G7H8I9J0}",
    "STATE_CANCEL_SHIPPED": "FLAG{STATE_CANCEL_SHIPPED_H8I9J0K1}",
    "STATE_CANCELLED_RESURRECT": "FLAG{STATE_CANCELLED_RESURRECT_I9J0K1L2}",
    "STATE_EXPIRED_PAY": "FLAG{STATE_EXPIRED_PAY_J0K1L2M3}",
    "STATE_DOUBLE_TRANSITION": "FLAG{STATE_DOUBLE_TRANSITION_K1L2M3N4}",
    "STATE_INVALID_INITIAL": "FLAG{STATE_INVALID_INITIAL_L2M3N4O5}",
    
    # 4.3 Return & Refund Flow (6 bugs)
    "RETURN_PARTIAL_THEN_FULL": "FLAG{RETURN_PARTIAL_THEN_FULL_M3N4O5P6}",
    "RETURN_REFUND_BEFORE_RECEIVE": "FLAG{RETURN_REFUND_BEFORE_RECEIVE_N4O5P6Q7}",
    "RETURN_REOPEN_REJECTED": "FLAG{RETURN_REOPEN_REJECTED_O5P6Q7R8}",
    "RETURN_DOUBLE_REFUND": "FLAG{RETURN_DOUBLE_REFUND_P6Q7R8S9}",
    "RETURN_EXCEED_TOTAL": "FLAG{RETURN_EXCEED_TOTAL_Q7R8S9T0}",
    "RETURN_FOOD_ACCEPTED": "FLAG{RETURN_FOOD_ACCEPTED_R8S9T0U1}",
    
    # 4.4 Inventory & Stock Logic (7 bugs)
    "STOCK_RESERVE_EXPIRE_CHECKOUT": "FLAG{STOCK_RESERVE_EXPIRE_CHECKOUT_S9T0U1V2}",
    "STOCK_CANCEL_NO_RESTORE": "FLAG{STOCK_CANCEL_NO_RESTORE_T0U1V2W3}",
    "STOCK_RETURN_DOUBLE_RESTORE": "FLAG{STOCK_RETURN_DOUBLE_RESTORE_U1V2W3X4}",
    "STOCK_OVERSELL_RACE": "FLAG{STOCK_OVERSELL_RACE_V2W3X4Y5}",
    "STOCK_NEGATIVE_ADJUST": "FLAG{STOCK_NEGATIVE_ADJUST_W3X4Y5Z6}",
    "STOCK_RESERVE_EXCEED": "FLAG{STOCK_RESERVE_EXCEED_X4Y5Z6A7}",
    "STOCK_PHANTOM_AVAILABLE": "FLAG{STOCK_PHANTOM_AVAILABLE_Y5Z6A7B8}",
    
    # 4.5 Discount & Pricing Logic (7 bugs)
    "DISCOUNT_REMOVE_KEEP_PERCENT": "FLAG{DISCOUNT_REMOVE_KEEP_PERCENT_Z6A7B8C9}",
    "DISCOUNT_VOLUME_THRESHOLD_ABUSE": "FLAG{DISCOUNT_VOLUME_THRESHOLD_ABUSE_A7B8C9D0}",
    "DISCOUNT_FLASH_SALE_PERSIST": "FLAG{DISCOUNT_FLASH_SALE_PERSIST_B8C9D0E1}",
    "DISCOUNT_STACK_FORBIDDEN": "FLAG{DISCOUNT_STACK_FORBIDDEN_C9D0E1F2}",
    "DISCOUNT_EXCEED_50_CAP": "FLAG{DISCOUNT_EXCEED_50_CAP_D0E1F2G3}",
    "DISCOUNT_EXPIRED_PROMO": "FLAG{DISCOUNT_EXPIRED_PROMO_E1F2G3H4}",
    "DISCOUNT_NEGATIVE_TOTAL": "FLAG{DISCOUNT_NEGATIVE_TOTAL_F2G3H4I5}",
    
    # 4.6 Loyalty Program Abuse (6 bugs)
    "LOYALTY_CANCEL_KEEP_POINTS": "FLAG{LOYALTY_CANCEL_KEEP_POINTS_G3H4I5J6}",
    "LOYALTY_RETURN_KEEP_POINTS": "FLAG{LOYALTY_RETURN_KEEP_POINTS_H4I5J6K7}",
    "LOYALTY_EARN_SPEND_SAME": "FLAG{LOYALTY_EARN_SPEND_SAME_I5J6K7L8}",
    "LOYALTY_DOUBLE_REDEEM": "FLAG{LOYALTY_DOUBLE_REDEEM_J6K7L8M9}",
    "LOYALTY_EXCEED_50_PERCENT": "FLAG{LOYALTY_EXCEED_50_PERCENT_K7L8M9N0}",
    "LOYALTY_NEGATIVE_BALANCE": "FLAG{LOYALTY_NEGATIVE_BALANCE_L8M9N0O1}",
    
    # 4.7 Payment & Checkout Flow (7 bugs)
    "PAYMENT_CART_MODIFIED_AFTER_INIT": "FLAG{PAYMENT_CART_MODIFIED_AFTER_INIT_M9N0O1P2}",
    "PAYMENT_DOUBLE_CHARGE": "FLAG{PAYMENT_DOUBLE_CHARGE_N0O1P2Q3}",
    "PAYMENT_IDEMPOTENCY_FAIL": "FLAG{PAYMENT_IDEMPOTENCY_FAIL_O1P2Q3R4}",
    "PAYMENT_PARTIAL_EXCEED": "FLAG{PAYMENT_PARTIAL_EXCEED_P2Q3R4S5}",
    "PAYMENT_CANCEL_AFTER_CONFIRM": "FLAG{PAYMENT_CANCEL_AFTER_CONFIRM_Q3R4S5T6}",
    "PAYMENT_COD_LIMIT": "FLAG{PAYMENT_COD_LIMIT_R4S5T6U7}",
    "PAYMENT_NEGATIVE_AMOUNT": "FLAG{PAYMENT_NEGATIVE_AMOUNT_S5T6U7V8}",
}


def get_flag(bug_id: str) -> str:
    """Return flag string for bug_id or empty string if unknown."""
    return FLAGS.get(bug_id, "")
